---
- name: Install helm
  hosts: masters
  gather_facts: true
  become: True
  become_user: root
  
  tasks:
    - name: Run rustup
      ansible.builtin.shell:
        cmd: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh
    
