---
- name: On Master Node - Create Token
  hosts: masters
  gather_facts: true
  become: True
  become_user: root
  tasks:

    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
 
    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
        
- name: On Worker Node - Join Cluster
  hosts: workers
  gather_facts: true
  become: True
  become_user: root
  tasks:
    - set_fact: var_two="test
    - name: join cluster
      shell: "{{ hostvars['masters'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
