---
- name: Post Install Steps
  hosts: openscap
  gather_facts: true
  become: True
  become_user: root
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: openscap.example.com
        use: systemd

    - name: Add users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop:
         - prayag
         - devops

    - name: Add user to sudoers
      lineinfile:
        dest: /etc/sudoers
        line: '{{ item }} ALL=(ALL) NOPASSWD: ALL'
      loop:
         - prayag
         - devops

    - name: Sleep for 100 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 100
      delegate_to: localhost    
           
    - name: Installing packages
      ansible.builtin.yum: pkg={{ item }}
      loop:
        - python3
        - python3-pip
        - epel-release
