---
- name: On all nodes - Installing Kubernetes using Kubeadm
  hosts: all
  gather_facts: true
  become: True
  become_user: root
  tasks:

    - name: Add prometheus-community repo
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"
        values_files:
          - prometheus-values.yaml
          
    - name: Deploy latest version of Prometheus chart inside monitoring namespace (and create it)
      kubernetes.core.helm:
        name: prometheus
        chart_ref: prometheus-community/prometheus
        release_namespace: monitoring
        create_namespace: true          


