---
- name: Install Docker, Jenkins, Plugins, and MySQL Client on Ubuntu 22.04
  hosts: localhost
  become: yes
  gather_facts: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # --- Docker installation ---

    - name: Install prerequisite packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        filename: docker

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Ensure Docker service is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes


    - name: Add user to docker group (replace 'ubuntu' if needed)
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Restart Jenkins to apply group membership changes
      systemd:
        name: jenkins
        state: restarted
