---
- name: OpenSCAP installation
  hosts: openscap
  gather_facts: true
  become: True
  become_user: root
  tasks:
           
    - name: Installing openscap packages
      ansible.builtin.yum: pkg={{ item }}
      loop:
        - openscap-scanner 
        - openscap-utils 
        - scap-security-guide
        - scap-workbench
        - httpd 

    - name: Restart service httpd
      ansible.builtin.service:
        name: httpd
        state: restarted

