---
- name: Install kubectl on Ubuntu using curl (with dynamic version)
  hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: Get latest stable kubectl version
      shell: curl -L -s https://dl.k8s.io/release/stable.txt
      register: kubectl_version_raw

    - name: Set kubectl download URL
      set_fact:
        kubectl_url: "https://dl.k8s.io/release/{{ kubectl_version_raw.stdout }}/bin/linux/amd64/kubectl"

    - name: Download kubectl binary
      get_url:
        url: "{{ kubectl_url }}"
        dest: /usr/local/bin/kubectl
        mode: '0755'


    - name: Verify kubectl installation
      command: kubectl version --client
      register: kubectl_version
      changed_when: false

    - name: Print kubectl version
      debug:
        msg: "{{ kubectl_version.stdout }}"
